### PR TITLE
GPL3 -> LGPL2.1

### LINKED ISSUE #72: Add a contributor copyright agreement to GitHub
**Is your feature request related to a problem? Please describe.**
The installer is licensed GPL, which means it cannot be included in propietary works such as impact without a separate license from the copyright owner (or both works being by the same entity).

This isn't a problem since we own both impact and the Installer, however if we accept third party contributions then we are no longer the sole copyright holder and would need to seek permission to use the installer in impact from all installer contributers.

**Describe the solution you'd like**
A Canonical-style copyright waiver that ensures ImpactDevelopment or Brady remains the sole copyright holder. A GitHub bot would enforce signing the waiver on any pr from a new contributer.

**Describe alternatives you've considered**
Alternatively, as the copyright holder we could change the license to LGPL, before allowing others to contribute and hold copyright over their changes.

**Additional context**

### PR DESCRIPTION
**Pull request by LeafHacker**
Change to a more permissive license to allow Impact to continue including Impact Installer while allowing third party contributions.

Approving this PR via a review will be taken as consent to re-license your contributions. I consent to my contributions being re-licensed.

Fixes #72

### CODE REVIEW

**Comment by leijurv** [comment]
Screen Shot 2019-09-21 at 10 22 32 PM


this is some BULL shit no FSF VIRUS FOR ME PLEASE

(in case you're unaware, the issue is that someone can fork the project, choosing to do so under LGPL3 (i.e. their fork is LGPL3, NOT LGPL2.1+), then you can't pull in their changes without upgrading to LGPL3) (since you can't pull in LGPL3 code into a LGPL2.1+ project since LGPL3 isn't compatible with basic LGPL2.1)

**Comment by leijurv** [comment]
please note that brady consented to a relicense under lgpl2.1 not lgpl2.1+ 😉

**Comment by LeafHacker** [comment]
My bad, didn't spot that. Will amend to specify 2.1 explicitly.

**Comment by 0-x-2-2** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
